mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls'))
]

posts/urls.py
from django.urls import path
from .views import index, manage, detail

app_name = "posts"
urlpatterns = [
  path('', index, name="index"),
  path('manage', manage, name="manage"),
  path('post/<int:post_id>', detail, name="detail")
]

posts/models.py
from django.db import models

class Post(models.Model):
  title = models.CharField(max_length=150)
  description = models.TextField(max_length=1500, null=True)
  created_at = models.DateTimeField(auto_now_add=True)
  updated_at = models.DateTimeField(auto_now=True)

  class Meta:
    ordering = ['-created_at']

class Comment(models.Model):
  text = models.CharField(max_length=450)
  post = models.ForeignKey(Post, on_delete=models.CASCADE)
  published = models.DateTimeField(auto_now_add=True)

  class Meta:
    ordering = ['-published']

posts/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib import messages
from django.urls import reverse

from .models import Post, Comment

def index(request):
  if request.method == "GET":
    posts = Post.objects.all()
    context = {
      "posts": posts
    }
    return render(request, "posts/index.html", context)

def manage(request):  
  if request.method == "GET":
    if request.GET.get("id"):
      id = request.GET.get("id")
      post = get_object_or_404(Post, pk=id)

      return render(request, "posts/manage.html", { "post": post })

    return render(request, "posts/manage.html")
  
  elif request.method == "POST" and request.POST.get("type") == "post":
    title = request.POST.get("title")
    description = request.POST.get("description")

    newPost = Post.objects.create(title=title, description=description)
    newPost.save()

    messages.success(request, "Post Created")
    
    return redirect("posts:manage")
  
  elif request.method == "POST" and request.POST.get("type") == "put":
    id = request.GET.get("id")
    post = get_object_or_404(Post, pk=id)
    newTitle = request.POST.get("title")
    newDescription = request.POST.get("description")

    post.title = newTitle
    post.description = newDescription
    post.save()

    messages.success(request, "Post Edited")

    return redirect("posts:manage")
  
  elif request.method == "POST" and request.POST.get("type") == "delete":
    id = request.GET.get("id")
    post = get_object_or_404(Post, pk=id)
    post.delete()

    messages.success(request, "Post Deleted")

    return redirect("posts:manage")

def detail(request, post_id):
  def text_format(text: str) -> list[str]:
    def add_format(split: str):
      if split == "\r":
        return "*&space*"
      elif split.endswith("\r"):
        return split[:len(split)-1]
      else:
        return split
    return list(map(add_format, text.split("\n")))

  post = get_object_or_404(Post, pk=post_id)

  if request.method == "GET":
    description_formated = []
    comments_formated = []

    if (post.description):
      description_formated = text_format(post.description)
    
    if request.GET.get("comments") == "show":
      comments = post.comment_set.all()
      for comment in comments:
        comments_formated.append({
          "text": text_format(comment.text),
          "published": comment.published
        })

    context = {
      "post": post,
      "description_formarted": description_formated,
      "comments": comments_formated
    }

    return render(request, 'posts/detail.html', context)
  
  elif request.method == "POST":
    textComment = request.POST.get("comment")
    newComment = Comment(text=textComment, post=post)
    url_redirection = reverse("posts:detail", kwargs={ "post_id": post_id }) + "?comments=show"
    newComment.save()

    messages.success(request, "Comment added")
    return redirect(url_redirection)

posts/templates/posts/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <style>
    * {
      padding: 0;
      margin: 0;
      box-sizing: border-box;
    }

    body {
      overflow-x: hidden;
      font-family: system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
      overflow-wrap: break-word;
    }

    .container {
      max-width: 1380px;
      width: 75%;
      margin: 0 auto;
    }

    .content {
      min-height: 100vh;
      margin-top: 3.5em;
      padding-bottom: 8em;
    }

    .footer {
      background-color: black;
      color: white;
      text-align: center;
      padding: 40px 0;
    }

    .header {
      background-color: black;
      color: white;
      height: 64px;
      display: flex;
      align-items: center;

      .header__items {
        display: flex;
        justify-content: space-between;

        span {
          font-weight: bold;
          font-size: 1.8em;
          font-family: monospace;
        }

        nav {
          display: flex;
          gap: 18px;

          a {
            color: white;
            text-decoration: none;
            font-weight: 500;
          }

          a:hover {
            color: orange;
            text-decoration: underline;
          }
        }
      }
    }
  </style>
  {% block head %}
  {% endblock %}
</head>
<body>
  <header class="header">
    <div class="container header__items">
      <span>Posts APP</span>
      <nav>
        <a href="{% url 'posts:index' %}">Posts</a>
        <a href="{% url 'posts:manage' %}">Manage Posts</a>
      </nav>
    </div>
  </header>

  <main class="container content">
    {% block content %}
    {% endblock %}
  </main>

  <footer class="footer">
    <p>© All Rights Recerved. </p>
  </footer>
</body>
</html>

posts/templates/posts/detail.html
{% extends "./base.html" %}

{% block head %}
  <title>Post #{{ post.id }}</title>
  <style>
    h1 {
      margin-bottom: 0.5em;
    }

    .section__footer {
      display: flex;
      gap: 1em;
      color: rgb(48, 48, 48);
      margin-top: 20px;
    }

    .items {
      display: grid;
      grid-template-columns: repeat(2, 1fr);
      margin-bottom: 2em;
    }

    .form {
      display: flex;
      flex-direction: column;
      align-items: center;
      gap: 12px;
    }

    .form h2 {
      text-align: center;
      color: rgb(92, 92, 92);
    }

    #comment {
      resize: none;
      padding: 4px;
    }

    .success {
      color: green;
      margin-bottom: 1em;
    }

    .comments__section {
      margin-top: 2.5em;
    }

    .comments {
      display: flex;
      flex-direction: column;
      gap: 1em;
    }

    .comment {
      border: 2px solid gray;
      list-style: none;
      padding: 10px 5px;

      time {
        display: block;
        color: rgb(94, 94, 94);
        margin-bottom: 1em;
      }
    }

    .comment_text {
      color: rgb(27, 27, 27);
      max-width: 90%;
    }
  </style>
{% endblock %}

{% block content %}
  <h1>{{ post.title }}</h1>

  <div class="items">
    <section>
      {% for text in description_formarted %}
        {% if text != "*&space*" %}
          <p>{{ text }}</p>
        {% else %}
          <br>
        {% endif %}
      {% endfor %}
  
      <footer class="section__footer">
        <p>Created At: {{ post.created_at }}</p>
        {% if post.created_at == post.updated_at %}
          <p>{{ post.updated_at }}</p>
        {% endif %}
      </footer>
    </section>

    <form action="" method="post" class="form">
      <h2>Add comment</h2>

      {% csrf_token %}
      <div>
        <textarea name="comment" id="comment" cols="30" rows="12" placeholder="Write a comment to this post." required></textarea>
      </div>
      <button>Add Comment</button>
    </form>
  </div>

  {% if messages %}
    {% for message in messages %}
      {% if "success" in message.tags %}
        <p class="success">{{ message }}</p>
      {% endif %}
    {% endfor %}
  {% endif %}

  <a href="{% url 'posts:detail' post.id %}?comments=show">Show Comments</a>

  <section class="comments__section">
    {% if "comments" in request.GET and request.GET.comments == "show" %}
      {% if comments %}
        <ul class="comments">
          {% for comment in comments %}
            <li class="comment">
              <time datetime="{{ comment.published }}">Published: {{ comment.published }}</time>
              {% for text in comment.text %}
                {% if text != "*&space*" %}
                  <p class="comment_text">{{ text }}</p>
                {% else %}
                  <br>
                {% endif %}
              {% endfor %}
            </li>
          {% endfor %}
        </ul>
      {% else %}
        <p>This post hasn't comments</p>
      {% endif %}
    {% endif %}
  </section>
{% endblock %}

posts/templates/posts/index.html
{% extends "./base.html" %}

{% block head %}
  <title>Posts App</title>
  <style>
    h1 {
      margin-bottom: 1.5em;
    }

    .posts {
      display: flex;
      flex-direction: column;
      gap: 10px;
    }

    .post {
      list-style: none;
    }

    .post__items {
      text-decoration: none;
      color: black;
      display: flex;
      justify-content: space-between;
      align-items: center;
      border: 2px solid gray;
      padding: 10px;
      height: 60px;

      .post__info {
        display: flex;
        align-items: center;
        gap: 12px;
      }
    }

    .post__items:hover {
      border-color: orange;

      h3 {
        color: orange;
        text-decoration: underline;
      }
    }
  </style>
{% endblock %}

{% block content %}
  <h1>Posts</h1>

  {% if posts %}
    <ul class="posts">
      {% for post in posts %}
        <li class="post">
          <a href="{% url 'posts:detail' post.id %}" class="post__items">
            <h3>{{ post.title }}</h3>
            <div class="post__info">
              <time datetime="{{ post.created_at }}">
                Created at: {{ post.created_at }}
              </time>
              <b>ID: {{ post.id }}</b>
            </div>
          </a>
        </li>
      {% endfor %}
    </ul>
  {% else %}
    <p>there are no posts.</p>
  {% endif %}
{% endblock %}

posts/templates/posts/manage.html
{% extends "./base.html" %}

{% block head %}
  <title>Manage Posts</title>
  <style>
    h1 {
      margin-bottom: 1.4em;
    }

    .forms {
      display: grid;
      grid-template-columns: repeat(2, 1fr);
      gap: 30px;
    }

    .forms form {
      border: 2px solid gray;
      padding: 20px 10px;
      height: fit-content;
    }

    .forms form h2 {
      text-align: center;
      margin-bottom: 1em;
    }

    .form__inputs {
      margin-bottom: 0.8em;
      margin-top: 0.4em;
    }

    .input {
      width: 100%;
      padding: 8px;
      resize: none;
    }

    .btn {
      padding: 0.5em 1em;
      border: none;
      background-color: rgb(40, 206, 40);
      cursor: pointer;
      color: white;
      font-weight: 600;
      width: 100%;
      font-size: 0.9em;
    }

    .btn:hover {
      background-color: rgb(34, 180, 34);
    }

    .form__inputs-consult {
      display: flex;
      gap: 8px;
      margin-bottom: 2.2em;
    }

    .form__inputs-consult .input {
      width: 90%;
    }

    .btn-consult {
      width: fit-content;
      background-color: rgb(64, 64, 236);
    }

    .btn-consult:hover {
      background-color: rgb(52, 52, 196);
    }

    .form__btns {
      display: grid;
      grid-template-columns: repeat(3, 1fr);
      gap: 18px;
    }

    .form__btns .btn {
      background-color: rgb(243, 61, 61);
    }

    .form__btns .btn:hover {
      background-color: rgb(194, 51, 51);
    }

    .form__btns .btn:nth-child(1) {
      background-color: rgb(41, 142, 189);
    }

    .form__btns .btn:nth-child(1):hover {
      background-color: rgb(33, 114, 151);
    }

    .form__btns .btn-cancel {
      background-color: gray;
      text-decoration: none;
      text-align: center;
    }

    .form__btns .btn-cancel:hover {
      background-color: rgb(97, 97, 97);
    }

    .success {
      padding: 10px;
      background-color: rgb(45, 133, 133);
      color: white;
      margin-bottom: 1em;
    }
  </style>
{% endblock %}

{% block content %}
  <h1>Manage Posts</h1>

  {% if messages %}
    {%for message in messages %}
      {% if 'success' in message.tags %}
        <p class="success">{{ message }}</p>
      {% endif %}
    {% endfor %}
  {% endif %}

  <div class="forms">
    <form method="post" action="{% url 'posts:manage' %}">
      {% csrf_token %}
      <h2>Create a new post</h2>
      <label for="title">Title</label>
      <div class="form__inputs">
        <input class="input" id="title" type="text" name="title" placeholder="Write Title Post">
      </div>

      <label for="description">Description</label>
      <div class="form__inputs">
        <textarea name="description" class="input" id="description" cols="30" rows="10" placeholder="(Optional) Write Description Post"></textarea>
      </div>

      <button class="btn" type="submit" name="type" value="post">
        Create
      </button>
    </form>

    <form 
      {% if post %}
        method="post"
      {% else %}
        method="get"
      {% endif %}
    >
      <h2>Edit or Delete a post</h2>
      {% if post %}
        {% csrf_token %}
        <label for="title">New Title</label>
        <div class="form__inputs">
          <input class="input" id="title" type="text" name="title" placeholder="Write New Title Post" value="{{ post.title }}">
        </div>
        <label for="description">New Description</label>
        <div class="form__inputs">
          <textarea name="description" class="input" id="description" cols="30" rows="10" placeholder="(Optional) Write New Description Post">{{ post.description }}</textarea>
        </div>
        <div class="form__btns">
          <button type="submit" class="btn" name="type" value="put">
            Edit
          </button>
          <button type="submit" class="btn" name="type" value="delete">
            Delete
          </button>
          <a href="{% url 'posts:manage' %}" class="btn btn-cancel">
            Cancel
          </a>
        </div>
      {% else %}
        <label for="consult">Consult</label>
        <div class="form__inputs form__inputs-consult">
          <input class="input" id="consult" type="text" name="id" placeholder="Write ID Post" required>
          <button type="submit" class="btn btn-consult">
            Consult
          </button>
        </div>
      {% endif %}
    </form>
  </div>
{% endblock %}